@startuml
Participant "combat : Combat" as s
Participant "monstre : Monstre" as coord #99FF99
Participant "aventurier : Aventurier" as c #99FF99
Participant "salle : Salle" as salle #99FF99
Participant "monstrePresent : ArrayList<Monstre>" as list #99FF99
Participant "coord : Coordonnee" as coordo #99FF99


->s : detecterCombat()
activate s

s->salle : getMonstrePresent()
activate salle
salle-->s : monstrePresent
deactivate salle

loop monstrePresent.size()
s->list : get(i)
activate list
list-->s :monstre
deactivate list
s->coord : getCoord()
activate coord
coord-->s : coord
deactivate coord

alt salle.getGrille[coord.getX()+1][coord.getY()].monstrePresent || salle.getGrille[coord.getX()-1][coord.getY()].monstrePresent || salle.getGrille[coord.getX()][coord.getY()+1].monstrePresent || salle.getGrille[coord.getX()][coord.getY()-1].monstrePresent
s->s : attaqueMonstre(monstre)
activate s
s-->s
deactivate s
end
end
<--s
deactivate s
@enduml