@startuml
Participant "salle : Salle" as s
Participant "listeMonstre : ArrayList<Monstre>" as liste #99FF99
Participant "monstre : Monstre" as m
Participant "a : Aventurier" as a

-> s : detecterCombat(Aventurier a)
activate s
loop i=0;i<listeMonstre.size();i++
s->liste : get(i)
activate liste
liste-->s : monstre
deactivate liste

alt (monstre.getCoor().getX()+1 == a.getCoor().getX() && monstre.getCoor().getY() == a.getCoor().getY()) || (monstre.getCoor().getX()-1 == a.getCoor().getX() && monstre.getCoor().getY() == a.getCoor().getY()) || (monstre.getCoor().getX() == a.getCoor().getX() && monstre.getCoor().getY()+1 == a.getCoor().getY()) || (monstre.getCoor().getX() == a.getCoor().getX() && monstre.getCoor().getY()-1 == a.getCoor().getY())

s->a : subirDegats(1)

activate a
a-->s
deactivate a
s->m : setDeplacementPossible(false)
else
s->m : setDeplacementPossible(true)
end
end
<--s

@enduml