@startuml
Participant "main" as m
create "donjon : Donjon" as d

m->d : new Donjon("donjon1")
create "nom : String" as nom
d->nom : nom = "donjon1"
activate d
create "etages : ArrayList<Etage>()" as list
d->list : new ArrayList<Etage>()

loop i=0; i < NUM_ETAGES;i++
d->list : add(new Etage(i)
activate list
list-->d
deactivate list
end
d-->m : donjon
deactivate d


@enduml