@startuml
Participant "salle : Salle" as s
Participant "m : Monstre" as m
Participant "alea : Aleatoire" as al
Participant "item : ArrayList<Item>" as item



->s : apparaitreLoot(m,alea)
activate s
s->m : getCoord()
activate m
m-->s : loot
deactivate m
s->alea : genererNombreAleatoire(0,100)
activate alea
alea-->s 
deactivate alea

alt random <= 30
create "potion : Potion" as po
s->po : new Potion(this,loot.getX(),loot.getY())
s->s : getItemPresent().add(potion)
activate s
s-->s
deactivate s
end
<--s
@enduml