@startuml
Participant "main" as m

create "etage : Etage" as e

m->e : new Etage(2)
create "this.numetage : Integer" as nume
e->nume : this.numetage = 2
activate e

create "this.salles : ArrayList<Salle>" as listS
e->listS : new ArrayList<Salle>()

loop int i = 0; i<NUM_SALLES;i++
e->listS : add(new Salle())
activate listS
listS-->e 
deactivate listS
end

loop int i=0; i < NUM_SALLES;i++
alt i==0

e->listS : get(i).getSortie().setSalleSuivante(salles.get(i+1))
activate listS
listS-->e
deactivate listS

e->listS : get(i).getEntree().setSallePrecedente(salles.get(NUM_SALLES-1))
activate listS
listS-->e
deactivate listS

else i==NUM_SALLES-1

e->listS : get(i).getSortie().setSalleSuivante(salles.get(0))
activate listS
listS-->e
deactivate listS

e->listS : get(i).getEntree().setSallePrecedente(salles.get(i-1))
activate listS
listS-->e
deactivate listS

else

e->listS : get(i).getSortie().setSalleSuivante(salles.get(i+1))
activate listS
listS-->e
deactivate listS

e->listS : get(i).getEntree().setSallePrecedente(salles.get(i-1))
activate listS
listS-->e
deactivate listS
end
end
e-->m : etage
@enduml