@startuml
Participant "aventurier : Aventurier" as av

participant "s : Salle" as s #99FF99
participant "s2 : Salle" as s2 #99FF99
participant "e : Escalier" as es #99FF99
participant "e : Etage" as e #99FF99

participant "grille : Case[][]" as grille #99FF99
participant "x : Int" as x #99FF99
participant "y : Int" as y #99FF99

-> av : changementEtage(s,c)
activate av
av->s : getGrille()
activate s
s-->av : grille
deactivate s

loop i=0 ; i < s.TAILLE_SALLES
loop j=0; j<s.TAILLE_SALES
alt grille[i][j] == c
av->x : x=i
activate x
x-->av
deactivate x
av->y : y=j
activate y
y-->av
deactivate y
end
end
end

av-> grille : grille[x][y]
activate grille 
grille --> av : Etage e
deactivate grille

av-> es : get EtageSup;
activate es
es--> av : Etage e
av -> es : getSalleEtageSup 
es --> av : Salle s2
deactivate es

av -> av : setEtage(e)
av -> av : setSalle(s2)
av -> av : setCoord(12,12)


<--av
deactivate av

@enduml