@startuml

Participant "aventurier:Aventurier" as aven
Participant "aventurier:Personnage" as paven #99FF99
Participant "grilleSalle : Case[][]" as grille #99FF99
Participant "c: Coordonnee" as cParam #99FF99

->aven : deplacerAventurier(c)
activate aven


alt c.getX() < grilleSalle.length && c.getX() >= 0) && (c.getY() < grilleSalle[0].length && c.getY() >= 0

alt grilleSalle[c.getX()][c.getY()].estTraversable()

aven->aven : getCase().setEstTraversable(true);
activate aven
aven-->aven
deactivate aven
aven->aven : changerCoord(c)
activate aven
aven-->aven
deactivate aven
aven->aven : getCase().setEstTraversable(false);
activate aven
aven-->aven
deactivate aven

alt grilleSalle[this.getCoor().getX()][this.getCoor().getY()]==this.getSalle().getEntree()

aven->aven : this.getSalle().getEntree().setEstTraversable(true)
activate aven
aven-->aven
deactivate aven

aven->aven : this.getSalle().getSortie().setEstTraversable(true)
activate aven
aven-->aven
deactivate aven


aven->aven : setSalle(this.getSalle().getEntree().getSallePrecedente())
activate aven
aven-->aven
deactivate aven
aven->paven : changementSalle(this.getSalle(),this.getSalle().getSortie())
activate paven
paven-->aven
deactivate paven

else grilleSalle[this.getCoor().getX()][this.getCoor().getY()]==this.getSalle().getSortie()

aven->aven : this.getSalle().getEntree().setEstTraversable(true)
activate aven
aven-->aven
deactivate aven

aven->aven : this.getSalle().getSortie().setEstTraversable(true)
activate aven
aven-->aven
deactivate aven

aven->aven : setSalle(this.getSalle().getSortie().getSalleSuivante())
activate aven
aven-->aven
deactivate aven
aven->paven : changementSalle(this.getSalle(), this.getSalle().getEntree())
activate paven
paven-->aven
deactivate paven

else grilleSalle[this.getCoor().getX()][this.getCoor().getY()]==this.getSalle().getEscalier()
aven->aven : changementEtage(this.getSalle().getEscalier().getSalleEtageSup(),this.getSalle().getEscalier().getEtageSup())
activate aven
aven-->aven
deactivate aven

end
end
<--aven : true
else
<--aven : false
end
deactivate aven

@enduml