@startuml
Participant "aventurier : Aventurier" as a
Participant "salle : Salle" as s
Participant "monstrePresent : ArrayList<Monstre>" as listM
Participant "monstre : Monstre" as m
Participant "stats : Stat" as sta

->a : attaque(12)
loop int i = 0; i<this.getSalle().getMonstrePresent().size();i++
alt monstre.getX() == this.getCoor().getX()+1 && monstre.getY() == this.getCoor().getY()) || (monstre.getX() == this.getCoor().getX()-1 && monstre.getY() == this.getCoor().getY()) || (monstre.getX() == this.getCoor().getX() && monstre.getY() == this.getCoor().getY()+1) || (monstre.getX() == this.getCoor().getX()+1 && monstre.getY() == this.getCoor().getY()-1)
activate a
a->a : getSalle()
activate a
a-->a : salle
deactivate a
a->listM : getMonstrePresent().get(i)
activate listM
listM-->a: monstre
deactivate listM
a->m : subirDegats(aventurier.getDegats())
activate m
m-->a
deactivate m

alt this.getSalle().getMonstrePresent().get(i).isMort()
a->sta : ajouterExp(this.getSalle().getMonstrePresent().get(i).getSTat().getExp())
activate sta
sta-->a 
deactivate sta
alt this.stat.getExp()==0
a->a : majStat()
activate a
a-->a 
deactivate a
end
end

end
end
<--a
@enduml