@startuml
Participant "monstre : Monstre" as s
Participant "grille[][] : Case" as coord #99FF99
Participant "grilleMonstreSpawn[][] : String" as spawn #99FF99
Participant "coord : Coordonnee" as c #99FF99
Participant "salle  Salle" as salle #99FF99

Participant "x : Coordonnee.x" as x #99FF99
Participant "y : Coordonnee.y" as y #99FF99

->s : deplacement()
activate s
s->c : getX()
activate c
c-->s : 6
deactivate c
s->c : getY()
activate c
c-->s : 3
deactivate c
s->salle : isSpawnPossible(7,3)
activate salle
salle-->s : true
deactivate salle



alt isSpawnPossible(7,3) = true
s->s : changerCoord(7,3)
activate s
s-->s
deactivate s
else isSpawnPossible(7,3) = false
s->salle : isSpawnPossible(5,3)
activate salle
salle-->s : true
deactivate salle
alt isSpawnPossible(5,3) =true
s->s : changerCoord(5,3)
activate s
s-->s
deactivate s
end
else isSpawnPossible(5,3) = false
s->salle : isSpawnPossible(6,4)
activate salle
salle-->s : true
deactivate salle

alt isSpawnPossible(6,4) =true
s->s : changerCoord(6,4)
activate s
s-->s
deactivate s
end
else isSpawnPossible(6,4) = false
s->salle : isSpawnPossible(6,2)
activate salle
salle-->s : true
deactivate salle
alt isSpawnPossible(6,4) =true
s->s : changerCoord(6,4)
activate s
s-->s
deactivate s
end
end
<--s
deactivate s




@enduml