@startuml
Participant "s : Salle" as Salle
Participant "tab_libre : ArrayList<Coordonnee>" as tab_libre
Participant "itemPresent : Arraylist<Item>" as itemPresent
Participant "aleaItem : Aleatoir" as aleaItem


-> Salle : placeAleatoirItem(aleaItem : Aleatoir)
loop : i=0;i<tab_libre.size();i++
activate Salle
Salle -> aleaItem : genererNombreAleatoire(0, 100)
aleaItem --> Salle : nbalea
Salle -> Salle : placelibreItems()
activate Salle
Salle --> Salle : tab_libre
deactivate Salle

alt : nbalea>=99
Salle -> tab_libre : get(i).getX()
activate Salle
activate tab_libre
tab_libre --> Salle
deactivate tab_libre
deactivate Salle
Salle -> tab_libre : get(i).getY()
activate Salle
activate tab_libre
tab_libre --> Salle
deactivate tab_libre
deactivate Salle
create "p : potion" as potion
Salle -> potion : "new potion(this,6,7)"
Salle -> itemPresent : add(p)
activate Salle
activate itemPresent
Salle <-- itemPresent
deactivate itemPresent
deactivate Salle
end
end
<-- Salle
deactivate Salle
@enduml