@startuml
Participant "s : Salle" as s
Participant "av : Aventurier" as av
Participant "itemPresent : ArrayList<Coordonnee>" as itemPresent
 -> s : prendreItem(av:Aventurier)
 activate s
 loop : int i=0;i<itemPresent.size();i++
 alt : av.getCoor().getX()==itemPresent.get(i).getCoo().getX()


 
 end
 end
<--s : false
deactivate s
@enduml