@startuml

participant "aventurier : Aventurier " as av
participant "coord : Coordonnee" as c #99FF99
participant "salle : Salle" as s #99FF99
participant "c : Coordonnee" as co #99FF99

->av : deplacerAventurier(coord)
activate av

alt coord.getX() < salle.getGrille().length && coord.getX() >= 0) && coord.getY() < salle.getGrille()[0].length && coord.getY() >= 0

alt salle.getGrille()[coord.getX()][coord.getY()].estTraversable()

av->av : changerCoord(coord)
activate av
deactivate av

alt salle.getGrille()[c.getX()][c.getY()]==salle.getEntree()
av->av : setSalle(salle.getEntree().getSallePrecedente())
activate av
deactivate av
else salle.getGrille()[coor.getX()][coor.getY()]==salle.getSortie()
av->av : setSalle(salle.getSortie().getSalleSuivante())
activate av
deactivate av
end
<--av:true
end
else
<--av : false
deactivate av
end

@enduml